hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd('gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"')
  hl.exec_cmd("rog-control-center")
  hl.exec_cmd("waybar")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("kdeconnect-indicator")
  hl.exec_cmd("waypaper --restore")
  hl.exec_cmd("swaync")
  hl.exec_cmd("glances -w")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("/home/jpsiquierolli/.config/hypr/scripts/smart_lock.sh")
  hl.exec_cmd("swww-daemon")
  hl.exec_cmd("eww daemon")
  hl.exec_cmd("sleep 2 && hyprctl reload")
  end)

