$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
$BROWSER = firefox


# Força o driver a usar o método de sincronização que não quebra no HDMI
env = WLR_DRM_NO_ATOMIC,1

# Garante que a aplicação saiba que deve usar a Nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

# Limita a fila de frames para evitar o "atropelo" no loading
env = __GL_MaxFramesAllowed,1

general {
    allow_tearing = true
}

misc {
    force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. :(
}
