# Remmina
windowrule = workspace 9, match:class org.remmina.Remmina
windowrule = monitor HDMI-A-1, match:class org.remmina.Remmina

# Spotify
workspace = 8, on-created-empty:[float] spotify
windowrule = workspace 8 silent, match:class spotify
workspace = 8, monitor:DP-1

# Supress maximize
windowrule = suppress_event maximize, match:class *

# Wofi
windowrule = no_blur on, match:class wofi
windowrule = opaque on, match:class wofi
windowrule = float on, match:class wofi

# Smart Gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

# Wofi
layerrule {
  name = layerrule-1
  blur = on
  ignore_alpha = 0.5
  animation = popin
  match:namespace = wofi
}

# Rocket League
windowrule = immediate 0, match:class RocketLeague

env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
