#!/usr/bin/env sh

text=$(date +%d\ %b) 

alt=$(date +'%A, %B %d, %Y')

tooltip=$(cal | sed -E ':a;N;$!ba;s/\r{0,1}\n/\\n/g')

printf '{"text": "%s", "alt": "%s", "tooltip": "%s"}\n' "$text" "$alt" "$tooltip"
